### ISSUE TITLE
[Modding question]

### ISSUE THREAD

**Issue by ghost** [Terasology/IRLCorp#12]
Id made a module and i would like to make it "craftable" with in this Case your mods furnace. (A lot of Special glass type Blocks and sth more). How can i make it "craftable" with your machines without editing IRLCorp ?

How do i set how it has to be crafted (Tool, how long does the Processing takes...) ?

Thanks in advance.

**Comment by ghost** [comment]
Sorry id mean the crusher not furnace. I hate my phones T9...

**Comment by Josharias** [comment]
Hi there gamecompiler!  In order to add to the existing crafting,  al you need is another "recipe" for the process.  There are a bunch already included for crushing and burning and such in ManualLabor (IRLCorp is dependent on this module) [here](https://github.com/Terasology/ManualLabor/tree/master/assets/prefabs/processes).  You can create more of them in your own module to accomodate any new process you may want.

Also, there are some defaults provided on the process definition itself that gets common process parts added for all processes of that type.  For example the [Crushing](https://github.com/Terasology/ManualLabor/blob/master/assets/prefabs/processDefinitions/Crushing.prefab) process has one second of time added to all of the child processes.  It was easier to change things en mass that way.

One more way you can customize the crafting stuff is to add a new process to a certain block. An example of this is the Assembly table which can do a number of things that are shared between blocks.  [See the assembly table block entity prefab](https://github.com/Terasology/ManualLabor/blob/master/assets/prefabs/blocks/AssemblyTable.prefab).

**Comment by ghost** [comment]
Ah ok, thank you. Are the assemblyProcess prefabs fetched automatically from my module?
Do i have to include the AssembleRawglass.prefab anywhere else ?
(Sorry for "include", i normally program C++ not Java, im not sure if it is the correct word)

So for example if id understood it correctly i could have to do it like that:

``` javascript
-----module/assets/prefabs/assemblyProcesses/AssembleRawglass.prefab-----

{
  "ProcessDefinition": {
    "processType": "ManualLabor:Crushing"
  },
  "ItemPrefabInput": {
    "itemCounts": {
      "Lotofglass:quartz_sand": 1,
      "Lotofglass:sodium": 1,
      "Lotofglass:calciumoxid": 2
    }
  },
  "BlockFamilyOutput": {
    "blockCounts": {
      "Lotofglass:Rawglass": 2
    }
  }
}

-----module/assets/blocks/Rawglass.block
{
   "translucent" : true,
    "shadowCasting" : false,
    "displayName": "Raw glass",
    "rotation" : "horizontal",
}
```

Thanks in advance.
Sorry for my bad english.

**Comment by ghost** [comment]
Got it work :dancer: 

Thank you for your help!

**Comment by Josharias** [comment]
Yes,  the workstation system will iterate through every prefab that has a ProcessDefinitionComponent that is in an enabled module.  

Your prefab looks about right.  The only comment I would make is that you would want to ensure that a workstation block has enough input inventory slots to accommodate 3 input item stacks for crushing purposes.

Possibly were you intending it to be an assembly process?  Judging by your folder path.  In which case you may want to use the Assembling process instead of Crushing.  `"processType": "ManualLabor:Assembling"`
